### ISSUE TITLE
Комментарии к заданию

### ISSUE THREAD

**Issue by alexander812** [bagrov/olymp-test#1]
1. загрузка компонентов из стора не очень удачная идея. Задача стора хранить стейт.
2. для передачи стора лучше было использовать Provider and inject из mobx-react либо Provider, Consumer из React
3. не стоит использовать bind внутри render
4. форматирование номера карты лучше делать c помощью маски
5. валидация номера карты позволяет ввести более 16 цифр
6. функцию validate лучше сделать простой

**Comment by bagrov** [comment]
@alexander812 по поводу первого пункта я написал комментарий к тестовому заданию, уже поправил

**Comment by bagrov** [comment]
Спасибо за фидбек

**Comment by bagrov** [comment]
Исправил первые 3 пункта

**Comment by bagrov** [comment]
Исправил все замечания

**Comment by alexander812** [comment]
Спасибо, посмотрю.
